global:
  scrape_interval: 1s

scrape_configs:
  - job_name: api
    static_configs:
      - targets:
          - 'api:8888'
        labels:
          service: analytics

  - job_name: clickhouse
    static_configs:
      - targets:
          - 'ch1:9363'
        labels:
          service: clickhouse
