global:
  scrape_interval: 1s

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: api
    # List of labeled statically configured targets for this job.
    static_configs:
      - targets:
          - 'api:8888'
        labels:
          service: analytics
